name: gilad
favicon: null
layout_spectrum: 0.4360411611851305
typography_spectrum: 0.8929139685351402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3069887983147055
  lightness: 0.6104754514526576
  saturation: 0.4914728307630867
  rhythmicContrast: 0.06974546331912279
purpose: []
